#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")

#@ if hasattr(data.values.cert_manager, "acme_host"):
#@ credentials = {}
#@ for domain in data.values.cert_manager.acme_domains:
#@ credentials[domain] = {"username": data.values.cert_manager.acme_username,
#@                        "password": data.values.cert_manager.acme_password,
#@                        "fulldomain": data.values.cert_manager.acme_full_domain,
#@                        "subdomain": data.values.cert_manager.acme_subdomain
#@                        }
#@ end
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: acme-dns
  namespace: #@ data.values.cert_manager.namespace
type: Opaque
#@ if hasattr(data.values.cert_manager, "acme_host"):
data:
  acmedns.json: #@ base64.encode(json.encode(credentials))
#@ else:
data: {}
#@ end
