#@ load("@ytt:data", "data")
#@ version = "v0.16.0"
---
name: "helm-values"
global:
  leaderElection:
    # Override the namespace used to store the ConfigMap for leader election
    namespace: #@ data.values.cert_manager.namespace
image:
    tag: #@ version
webhook:
    image:
        tag: #@ version
cainjector:
    image:
        tag: #@ version
extraArgs: 
    -  #@ "--cluster-resource-namespace={}".format(data.values.cert_manager.namespace)
    - --enable-certificate-owner-ref=true
