#@ load("@ytt:data", "data")
---
name: "helm-values"
global:
  leaderElection:
    # Override the namespace used to store the ConfigMap for leader election
    namespace: #@ data.values.cert_manager.namespace
installCRDs: true
extraArgs: 
    -  #@ "--cluster-resource-namespace={}".format(data.values.cert_manager.namespace)
    - --enable-certificate-owner-ref=true
